### ISSUE TITLE
[Technical] Dependency Injection of MUI

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#103]
- theme 
- icons
common/hooks
common/icons

für SHK

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-RAK/HASKI-Frontend/103?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura
