### ISSUE TITLE
[Technical] Implementation of client-sided routing

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#110]
**Technical**

Implementation of client-sided routing
 
**Problem description**

React Routing only provides server-sided routing. Therefore client-sided routing is need to access nested pages from root.

**Possible approch**

- https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

**Acceptance criteria**

- [ ] Nested pages are directly accessed from root page

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Comment by Platura** [comment]
Temporary fix with Hashrouter. For a cleaner solution a change to our Routing System would be need. (Isomorphic, usw.)

**Comment by theUpsider** [comment]
- Ordner neu zuordnen
- Tests von Pages trennen
- Struktur anlegen von vorher
