### ISSUE TITLE
[Technical] Implementation of general debounce function

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#111]
**Technical**

- Create a service function to debounce functions
- Located under services
 
**Problem description**

Debouncing is implmenent in typescript via timeout. To not flood the code with various timeout function a abstract debounce function is needed to outsource some boilerplate code.

**Possible approch**

- https://www.freecodecamp.org/news/debouncing-explained/
- https://stackoverflow.com/questions/23123138/how-to-perform-debounce
- https://blog.logrocket.com/create-custom-debounce-hook-react/
- Look at ProjectDescriptionStepper.hooks, ProjectDescriptionCard.hooks and Searchbar for more information of timeout usage

**Acceptance criteria**

- [ ] Debounce function is successfully implemented
- [ ] timout functions were replaced with debounce function

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs
- [ ] Rendering behaviour is optimized

**Comment by theUpsider** [comment]
Hat Martina

**Comment by theUpsider** [comment]
Hat Martyna immernoch.
