### ISSUE TITLE
[Technical] Application logic to sort glossary entries

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#112]
translationn script extend to sort json arrays

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-RAK/HASKI-Frontend/112?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura
