### ISSUE TITLE
Create News Banner Component

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#118]
**Component**

Create News Banner Component
 
**Acceptance criteria**

- [ ] Component can be accessed
- [ ] Component represents all needed information
- [ ] Component is accessible from root page
- [ ] Can be closed by user, (localstorage, appears if new news in Backend)

 **Definition of Ready**

- [ ] Component is small enough for Sprint
- [ ] Component is clearly understandable for everyone involved
- [ ] Component effort is estimated
- [ ] Component has acceptance criteria
- [ ] Component has added value for the product or development
- [ ] Component origin is known (stakeholder)
- [ ] Component is assigned to Release
- [ ] Backend and Frontend are cloned from GitHub and Running locally
- [ ] Basic knowledge of the backend and frontend architecture
- [ ] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the Component has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Technical Definition of Done**

- [ ] Get references from other applications/websites
- [ ] Create wireframe
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

**Comment by DimitriB01** [comment]
![language](https://github.com/HASKI-RAK/HASKI-Frontend/assets/92084464/692927fa-95f0-4a68-ac74-a6a6358448de)
