### ISSUE TITLE
Create Local Nav Component

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#126]
**Component/Page**

As a role I want functionality so that value
As a student I want to navigate in the local context so that I can access similar topics fast.
 
**Acceptance criteria**

- [x] Component/Page can be accessed
- [x] Component/Page represents all needed information
- [x] Component/Page is accessible from root page

 **Definition of Ready**

- [x] Component/Page is small enough for Sprint
- [x] Component/Page is clearly understandable for everyone involved
- [x] Component/Page effort is estimated
- [x] Component/Page has acceptance criteria
- [x] Component/Page has added value for the product or development
- [x] Component/Page origin is known (stakeholder)
- [x] Component/Page is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [x] All acceptance criteria are met
- [x] The implementation of the Component has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [x] A code review has been performed (or created in pairing program)
- [x] Code conventions are followed
- [x] Unit test coverage must be greater than 90% 
- [x] All tests must have passed
- [x] Technical documentation created (Feature documented in GitHub Wiki)
- [x] UML class diagrams and component diagrams created and up-to-date
- [x] Documentation in realization created (source code)
- [x] Changelog created (Clear description in merge request)
- [x] There are no known bugs

**Technical Definition of Done**

- [x] Get references from other applications/websites
- [x] Create wireframe
- [x] Everything build out of Material UI components
- [x] New Material UI components capsulated via dependency injection in "@common/components"
- [x] Provide basic information pieces in comments
- [x] Establish interface to backend (if necessary) 
- [x] Use Skeleton components if something has to be fetched (if necessary)
- [x] Error management: Components should handle undefined inputs
- [x] Components should be resuable (if possible)
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

**Comment by theUpsider** [comment]
Tests for Errorhandling by Joel pending.
