### ISSUE TITLE
Questionnaire Results are fetched for each student

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#154]
**Technical**

Fetch questionnaire Results for current User from Database.
 
**Problem description**

**Possible approch**

**Acceptance criteria**

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-RAK/HASKI-Frontend/154?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura
