### ISSUE TITLE
User has to accept Privacy Policy before he logs in

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#195]
**User Story**

As a student i want to be able to accept the Privacy Policy, before i enter the page.

**Acceptance criteria**

- [x] After clicking the Login Button a Modal opens that asks the user if he accepts the Privacy Policy
- [x] Modal opens every time (if localstorage["consent"] = false | unset)

 **Definition of Ready**

- [x] User Story is small enough for Sprint
- [x] User Story is clearly understandable for everyone involved
- [x] User Story effort is estimated
- [x] User Story has acceptance criteria
- [x] User Story has added value for the product or development
- [x] User Story origin is known (stakeholder)
- [x] User Story is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [x] Code conventions are followed
- [x] Unit test coverage must be greater than 90% 
- [x] All tests must have passed
- [x] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [x] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [x] There are no known bugs

**Comment by DimitriB01** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-RAK/HASKI-Frontend/195?planning-poker) with Zenhub @KLee954 @Platura @theUpsider @juli-txt

**Comment by theUpsider** [comment]
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/25013640/60d51989-cd85-42a9-8702-bc323fa3b5dd)

**Comment by DimitriB01** [comment]
Additional: If the user does not allow our functional Cookies he will be redirected  to a "blank" Page. Telling him, he can not use the system without cookies. If he reconsidered, then he can update his cookie policy (open the cookie policy again). (optional: A cool meme to make the reconsider their choice)
