### ISSUE TITLE
[Technical] Rename translation identifiers

### ISSUE THREAD

**Issue by juli-txt** [HASKI-RAK/HASKI-Frontend#216]
**Technical**

Change the casing and naming of translation (internationalization). We want a distinct way of naming components and pages in i8next. e.g: "pages.pricacypolicy" instead of "pages.Privacy-PoliCy".
1. format like:
- components.LoginForm.submit
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--304a91dd12ab0d521069d5f0121bdc669eff8931/grafik.png)

2. rename all translations based on the format
3. document it how future developers need to name their translations
 
**Problem description**
We have inconsitent naming which leads to confusing names:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9kQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ffd75e6a4ea0c9cefbb775dc32bd12ebffa5fe6/grafik.png)

**Possible approch**

- rename everything

**Acceptance criteria**

- [ ] everything is in the same format
- [ ] renamed

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs
- [ ] Rendering behaviour is optimized

**Comment by DimitriB01** [comment]
https://trello.com/c/s5gOfzfu/34-i18next-translationfiles-naminconvention-im-frontend-anpassen
