### ISSUE TITLE
[Technical] Remove Login with credentials

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#265]
**Technical**

Alot of students are confused why they can not login. Therefore we have to make it easier for them and remove the Credentials-Login. The Login Button "Moodle" need to be renamed to something like "Login with HASKI credentials *HASKI Logo*"

[Private Zenhub Image]
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/92084464/95bb551a-0c80-4e29-ad11-4a4e88c45315)

**Possible approch**

- Remove Moodle-Login button and functionality
- Research RestAPI calls to Moodle, and if it is possible to get a cookie or if the login-token is sufficient

**Acceptance criteria**

- [x] Button and Functionality removed
- [ ] Login works with username and password

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs
- [ ] Rendering behaviour is optimized

**Comment by theUpsider** [comment]
suggestion: dont show username and password field, just moodle login button and name it: log in using Moodle or something like this:

**Comment by theUpsider** [comment]
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/25013640/828369c0-9080-4c7a-ac2f-689f3a1dc0e3)
Example miro

**Comment by DimitriB01** [comment]
We discussed this topic in the Frontend team. We think it would be best if the user never gets the information that a Moodle exists in the background. As they are always confusing the 2 links (frontend and moodle) with each other. 

You are right it is way more safe and technically a better way doing it with oauth. Maybe we should never say, that they are logging in with moodle and only something like "Login with your Data". Still  it is a minor inconvinience that they will see the moodle URL for potential confusion

**Comment by DimitriB01** [comment]
We could think about a modal that opens upon clicking on the button, where the user can only login and will not directly see the Moodle-URL

**Comment by Platura** [comment]
![Bild_2023-12-13_101619909](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/4f0878f0-07ec-4f89-bc4e-1689d75d6e98)

This is how generally a Login would look with only the moodle button. Button color would need to be changed

**Comment by DimitriB01** [comment]
Looks good, could you remove the moodle logo and exchange it with our haski logo and text.

**Comment by Platura** [comment]
![IdeeLogin](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/eab2d278-4f5f-4d90-b646-cf5de9be9230)

**Comment by Platura** [comment]
![square](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/0983c3e0-2a25-45e5-866f-1a14e3bb6f96)

Login with the haski logo. One with a round imagewrapper, one with a square image wrapper

**Comment by Platura** [comment]
![whiteButton](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/cd778a72-f43e-46a5-a941-d836042a032a)
Logo with a newly added white button

**Comment by Platura** [comment]
![changed text](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/e028c8b8-f94e-4f41-9207-d15417991910)
![differentTextandOrangeButton](https://github.com/HASKI-RAK/HASKI-Frontend/assets/80248709/d2347d6a-6516-4068-a412-7789708d3200)

Tried out some more

**Comment by DimitriB01** [comment]
I think the last one looks pretty good. Could you add the white circle around the haski logo and then send it in our discord to ask the other colleagues about their opinion
