### ISSUE TITLE
[Technical] Make moodle videos a little bit prettier

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#272]
**Technical**

Videos in the iFrame can be big at the beginning with the Moodle Setting: Display = open. 
The Moodle theme has rules, how to embed the video in the page. This can be made a little bit prettier so that the video sits perfectly in our Frontend iFrame.

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs
- [ ] Rendering behaviour is optimized

**Comment by KLee954** [comment]
Was already solved by setting Display to open in module settings.

**Comment by KLee954** [comment]
![videoexample](https://github.com/HASKI-RAK/HASKI-Frontend/assets/67826694/0da57289-0cd1-4812-b772-30f4c94d56a4)
![filesettings](https://github.com/HASKI-RAK/HASKI-Frontend/assets/67826694/b6c599fb-ffa7-4a2f-afaa-142eb56fe3e8)
