### ISSUE TITLE
Learning Elements with the same classification should be displayed in a group besides each other

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#276]
**User Story**

As a student i want to see all Learning Elements with the classification, besides each other in a group (like Übung) 

**Possible Approach**
Either filter the classifications for all classifications (like Übung right now)
Or go through the array and create a group if more than 1 classification comes after each other (classifications have the same position in the learning Path)
 

**Acceptance criteria**

- [ ] 1 classification is diplayed as before
- [ ] more than 1 classification is displayed in a group and the elements in the group are displayed besides each other

 **Definition of Ready**

- [ ] User Story is small enough for Sprint
- [ ] User Story is clearly understandable for everyone involved
- [ ] User Story effort is estimated
- [ ] User Story has acceptance criteria
- [ ] User Story has added value for the product or development
- [ ] User Story origin is known (stakeholder)
- [ ] User Story is assigned to Release
- [ ] Backend and Frontend are cloned from GitHub and Running locally
- [ ] Basic knowledge of the backend and frontend architecture
- [ ] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Comment by juli-txt** [comment]
![Topic](https://github.com/HASKI-RAK/HASKI-Frontend/assets/106922840/5078331d-c4d7-4227-9188-018bdb268d80)
