### ISSUE TITLE
Create Questionnaire component

### ISSUE THREAD

**Issue by theUpsider** [HASKI-RAK/HASKI-Frontend#3]
**User Story**

As a student/anonymous student I want to do a questionnaire so that my learning type can be determined. 

**Acceptance criteria**

- [x] Feedback activity in Moodle (dummy data) is created
- [ ] Backend persists result from feedback activity associated to the user
- [ ] Publish Moodle course and consume questionnaire in HASKI

 **Definition of Ready**

- [x] User Story is small enough for Sprint
- [x] User Story is clearly understandable for everyone involved
- [x] User Story effort is estimated
- [x] User Story has acceptance criteria
- [x] User Story has added value for the product or development
- [x] User Story origin is known (stakeholder)
- [x] User Story is assigned to Release
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue

**Definition of Done**

- [ ] All acceptance criteria are met
- [ ]  The implementation of the User Story has been successfully accepted by the Product Owner
- [ ]  The implementation is in GitHub
- [ ]  A code review has been performed (or created in pairing program)
- [ ]  Code conventions are followed
- [ ]  Unit test coverage must be greater than 90%
- [ ]  All tests must have passed
- [ ]  Technical documentation created (Feature documented in GitHub Wiki)
- [ ]  UML class diagrams and component diagrams created and up-to-date
- [ ]  Documentation in realization created (source code)
- [ ]  Changelog created (Clear description in merge request)
- [ ]  There are no known bugs

**Comment by theUpsider** [comment]
Hey @juli-txt I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/haski-ws-63317fe9ca1e282770a9342a/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by juli-txt** [comment]
![Questionnaire_Activity_Diagram](https://user-images.githubusercontent.com/106922840/197520823-398a5b3a-4183-4e33-8a6c-91f61a3d5610.png)

**Comment by juli-txt** [comment]
# Questionnaire-Activity-Download-URL:
`/mod/questionnaire`: Which kind of activity
`/report.php`: Shows answers if activity has been completed by atleast one user

## Example:
`http://localhost/mod/questionnaire/report.php?sesskey=ec2aar5S2T&choicecodes=1&choicetext=1&downloadformat=csv&instance=1&user=2&sid=1&action=dfs&group=0`

**Comment by juli-txt** [comment]
https://moodle.org/plugins/view.php?plugin=mod_questionnaire

**Comment by theUpsider** [comment]
Wird gererendert wenn radio button gedrückt wird. Cedric ist da dran.
