### ISSUE TITLE
Create a Springer-Link Tutorial Video

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#311]
**User Story**
 Create a video showing the steps to download a source from springer link

**Acceptance criteria**

- [ ] Video was recorded with mouse and keyboard connected
- [ ] Acceptance Criterion 2

 **Definition of Ready**

- [ ] User Story is small enough for Sprint
- [ ] User Story is clearly understandable for everyone involved
- [ ] User Story effort is estimated
- [ ] User Story has acceptance criteria
- [ ] User Story has added value for the product or development
- [ ] User Story origin is known (stakeholder)
- [ ] User Story is assigned to Release
- [ ] Backend and Frontend are cloned from GitHub and Running locally
- [ ] Basic knowledge of the backend and frontend architecture
- [ ] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [ ] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [ ] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Comment by Platura** [comment]
Videos sind fertig und sind unter HASKI-Extern\05-DomaenenModell\02-Lernelemente\Kempten\Videotutorials 
in der nextcloud

**Comment by DimitriB01** [comment]
Jim Review
[Generell] Mauszeiger hervorheben = z.B. größer und grün
[0:03] Korrektur: Text korrigieren = Klicken Sie auf den Link der Zusatzliteratur
[0:36] Korrektur: Text korrigieren = So erhalten Sie online ein Buch über die Hochschulbibliothek
[1:11] Text verschieben, sodass er komplett auf weißem Hintergrund ist. Z.B. Rechts weiter unten. 
[1:11] Hier nach dem selben Titel und Autor suchen, wie bereits in der ersten Hälfte des Videos gezeigt. 
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/92084464/07cef426-bbe3-4a0b-b5a9-9dcb3714d833)

**Comment by Platura** [comment]
Hab die Änderungen umgesetzt kann jetzt unter dem selben Ordner angeschaut werden

**Comment by DimitriB01** [comment]
Jim Review:
[0:04] Der Part nachdem man auf den link geklickt hat und sich mit der Institution anmelden soll fehlt nun.
[1:11] Hier nach dem selben **Titel und Autor** suchen, wie bereits in der ersten Hälfte des Videos gezeigt. -> Damit kommt nur 1 Ergebnis und man muss nicht suchen/scrollen.

**Comment by Platura** [comment]
geänderte Videos sind jetzt in nextcloud
