### ISSUE TITLE
HASKI-Anleitung aktualisieren

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#316]
Da einige Features in unser Frontend hinzugekommen ist, ist die Anleitung nicht mehr aktuell. 
Ich denke man muss hauptsächlich die Screenshots austauschen. Und mal durchlesen und sonstige Informationen aktualisieren. 

Das gilt für die deutsche Anleitung:
https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/628454?filePath=%2FHASKI-Extern%2F10-Standorte%2FKempten%2FEvaluation%20November%202023%2FKempten_Tutorial_zur_Bedienung_von_HASKI_Nov23_v4.docx

und englische Anleitung:
https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/628435?filePath=%2FHASKI-Extern%2F10-Standorte%2FKempten%2FEvaluation%20November%202023%2FKempten_Instructions%20and%20tutorial%20for%20operating%20the%20HASKI-system_Nov23_english_v1.docx

**Comment by Platura** [comment]
neuer ordner wurde unter \\Nextcloud\HASKI-Extern\10-Standorte\Kempten\Evaluation SoSe2024 angelegt und enthält die überarbeiteten Anleitungen
