### ISSUE TITLE
[Bug] Newsbanner Bug

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#344]
**Technical**

Newsbanner is visible only after the user selects a language from the drop down. (It has to be the other language)
Reloading the page or navigating in the system does not solve the problem.
Problem occurs with and without authentication as student.

Fresh on Page:
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--347466ef1853ddda03c067a8c526aa0a442abeb1/%7B930C947E-938F-4871-B373-96C2524852E9%7D.png" alt="{930C947E-938F-4871-B373-96C2524852E9}.png" />

After selecting a language (Did not show anything after login, only after changing language):
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c864d5a456ef6ff1534322e9e59687cd4652527/%7B01C8DF3F-2F0D-4DE2-ABBF-7B0FEBACB357%7D.png" alt="{01C8DF3F-2F0D-4DE2-ABBF-7B0FEBACB357}.png" />

**Comment by Platura** [comment]
Found a problem in the backend: The tests and the db_setup use HS-AS. Needs to be changed to TH-AB. I will create an issue to fix this.
