### ISSUE TITLE
Create Glossary page

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#52]
**User Story**

As student i want to see the Glossary page.
 

**Acceptance criteria**

- [x] Glossary page can be accessed
- [x] Glossary page represents all needed information
- [x] Glossary page is accessible from HASKI-course root page

 **Definition of Ready**

- [x] User Story is small enough for Sprint
- [x] User Story is clearly understandable for everyone involved
- [x] User Story effort is estimated
- [x] User Story has acceptance criteria
- [x] User Story has added value for the product or development
- [x] User Story origin is known (stakeholder)
- [x] User Story is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue
 
**Common Definition of Done**

- [x] All acceptance criteria are met
- [ ] The implementation of the User Story has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [ ] A code review has been performed (or created in pairing program)
- [ ] Code conventions are followed
- [ ] Unit test coverage must be greater than 90% 
- [ ] All tests must have passed
- [ ] Technical documentation created (Feature documented in GitHub Wiki)
- [x] UML class diagrams and component diagrams created and up-to-date
- [ ] Documentation in realization created (source code)
- [ ] Changelog created (Clear description in merge request)
- [ ] There are no known bugs

**Technical Definition of Done**
- [x] #85
- [x] Informationsstücke auflisten (Begriff : string, Erklärung : string)
- [x] Wireframe erstellen
- [x] Skelett-Komponente in Projekt anlegen
- [x] Schnittstellen bauen (fetch, store)
- [x] API-Schnitstelle in Backend einbauen bzw. mit Marc abklären (Daten existieren in JSON im Frontend)
- [x] Errormanagement (Mindset: mit leeren Informationen umgehen (undefined) -> Unser System crasht nicht)
- [x] Loading Statemanagement (Skeleton MUI für alles, was gefetcht wird)
- [x] Reusable Components and Functions
- [x] Style Guide konsultieren -> in HASKI Mindset verfallen (aktuell nicht umsetzbar)
- [x] UX-Review (alle Planes beachten, für Reviewer wichtig)
- [x] Material UI verwenden (Größe, Alignment, Layout)
- [x] Accessibility (aktuell nicht umsetzbar)
- [x] #86
- [x] Testing

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/52?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura

**Comment by juli-txt** [comment]
`{
    "glossaryElementsGerman": [
        {
            "term": "Titel", // String
            "definition": "Definition", // String
            "sources": "Quellen", // String
            "tags": [ "Tags" ] // Array
        }
    ],
    "glossaryElementsEnglish": [
        {
            "term": "Title", // String
            "definition": "Definition", // String
            "sources": "Sources", // String
            "tags": [ "Tags" ] // Array
        }
    ]
}`

**Comment by juli-txt** [comment]
![GlossaryPage](https://user-images.githubusercontent.com/106922840/223418115-ef5aa49d-01b5-4bfb-8e83-04c75dc6f945.png)
