### ISSUE TITLE
Create HASKI-contact page

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#69]
**User Story**

As a student I want to be able to see the HASKI-contact page.
 

**Acceptance criteria**

- [x] HASKI-contact page can be accessed
- [x] HASKI-contact page represents all needed information
- [x] HASKI-contact page is accessible from the HASKI-course root page

 **Definition of Ready**

- [x] User Story is small enough for Sprint
- [x] User Story is clearly understandable for everyone involved
- [x] User Story effort is estimated
- [x] User Story has acceptance criteria
- [x] User Story has added value for the product or development
- [x] User Story origin is known (stakeholder)
- [x] User Story is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [x] All acceptance criteria are met
- [x] The implementation of the User Story has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [x] A code review has been performed (or created in pairing program)
- [x] Code conventions are followed
- [x] Unit test coverage must be greater than 90% 
- [x] All tests must have passed
- [x] Technical documentation created (Feature documented in GitHub Wiki)
- [x] UML class diagrams and component diagrams created and up-to-date
- [x] Documentation in realization created (source code)
- [x] Changelog created (Clear description in merge request)
- [x] There are no known bugs

**Technical Definition of Done**

- [x] Referenzen von anderen websiten holen
- [x] informaitonsstücke auflisten (begriff : string, erklärung : string)
- [x] wireframe erstellen
- [x] skelett komponente in projekt anlegen
- [x] schnitstellen bauen (fetch, store)
- [x] API Schnitstelle in backend einbauen bzw. mit Marc abklären
- [x] error management (mindset: mit leeren informationen umgehen -> unser system crasht nicht)
- [x] loading state management (skeleton MUI für alles was gefetcht wird)
- [x] wiederverwndbarkeit?
- [x] style guide consultieren -> in HASKI Mindset verfallen
- [x] UX Review (alle planes beachten)
- [x] material UI zeuigs (größe, alignment)
- [x] accessibility
- [x] #86 
- [x] testing
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/69?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura
