### ISSUE TITLE
Questionnaire Results Page is created

### ISSUE THREAD

**Issue by DimitriB01** [HASKI-RAK/HASKI-Frontend#90]
**User Story**

As a student I want be able to see the results of the Questionnaire
 

**Acceptance criteria**

- [x] Questionnaire results page is accessable
- [x] Page has all the needed information
- [x] Graphs and tables are shown correctly
- [x] Page is accessable in english and german

 **Definition of Ready**

- [x] User Story is small enough for Sprint
- [x] User Story is clearly understandable for everyone involved
- [x] User Story effort is estimated
- [x] User Story has acceptance criteria
- [x] User Story has added value for the product or development
- [x] User Story origin is known (stakeholder)
- [x] User Story is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [x] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [x] All acceptance criteria are met
- [x] The implementation of the User Story has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [x] A code review has been performed (or created in pairing program)
- [x] Code conventions are followed
- [x] Unit test coverage must be greater than 90% 
- [x] All tests must have passed
- [x] Technical documentation created (Feature documented in GitHub Wiki)
- [x] UML class diagrams and component diagrams created and up-to-date
- [x] Documentation in realization created (source code)
- [x] Changelog created (Clear description in merge request)
- [x] There are no known bugs

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/90?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura

**Comment by DimitriB01** [comment]
![QuestionnaireResults](https://user-images.githubusercontent.com/92084464/218064348-79594b45-36cb-4a98-8919-561ebd9f5094.png)
