### ISSUE TITLE
[Technical] Logging

### ISSUE THREAD

**Issue by theUpsider** [HASKI-RAK/HASKI-Frontend#95]
For debugging and finding errors in deployment, we need a logging service.
https://meticulous.ai/blog/getting-started-with-react-logging/
Implement with security and buffer so no constant spam to backend.

How to make logger global + dependency injection:
https://github.com/pimterry/loglevel#typescript

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/95?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura

**Comment by DimitriB01** [comment]
added new Library "loglevel": https://yarnpkg.com/package/loglevel

**Comment by DimitriB01** [comment]
![image](https://user-images.githubusercontent.com/92084464/221576888-c034ce00-b196-471a-95d3-2f811de84bd6.png)

**Comment by DimitriB01** [comment]
A Ringbuffer class got added. It can be initialized with any size, and can hold any defined elements. 
If an element exceeds the size, the first element in the list gets deleted. 

The logBuffer.config class describes a global RingBuffer with a set size and structure to hold all log messages. It gets called in the App class.

**Comment by DimitriB01** [comment]
In the logBuffer.config class, it is possible to define what happens when the log. method is called. 
For example -> the message should be displayed in the console and the message and the current date should be added to the Global Ringbuffer. Here we could define, what happens if an log.error is called.
