### ISSUE TITLE
[Research] website layout and masks for learning context

### ISSUE THREAD

**Issue by theUpsider** [HASKI-RAK/HASKI-Frontend#96]
[Trello](https://trello.com/c/Fh6cJtI4/324-website-layout-und-mocks)

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/96?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura

**Comment by DimitriB01** [comment]
Path: Nextcloud\HASKI-Extern\06-Frontend\03-UX\Wireframe Photos
