### ISSUE TITLE
Create Snackbar Messages

### ISSUE THREAD

**Issue by theUpsider** [HASKI-RAK/HASKI-Frontend#98]
**Component**

Create Snackbar Messages
 
**Acceptance criteria**

- [x] Snackbars can be shown
- [x] Snackbars represents all needed information
- [x] Snackbars can be seen from every page

 **Definition of Ready**

- [x] Create Snackbars is small enough for Sprint
- [x] Create Snackbarsis clearly understandable for everyone involved
- [x] Create Snackbars effort is estimated
- [x] Create Snackbars has acceptance criteria
- [x] Create Snackbars has added value for the product or development
- [x] Create Snackbars origin is known (stakeholder)
- [ ] Create Snackbars is assigned to Release
- [x] Backend and Frontend are cloned from GitHub and Running locally
- [x] Basic knowledge of the backend and frontend architecture
- [ ] Activity diagram (or sequence diagram) screenshot in issue
 
**Definition of Done**

- [x] All acceptance criteria are met
- [ ] The implementation of the Component has been successfully accepted by the Product Owner
- [x] The implementation is in GitHub
- [x] A code review has been performed (or created in pairing program)
- [x] Code conventions are followed
- [x] Unit test coverage must be greater than 90% 
- [x] All tests must have passed
- [x] Technical documentation created (Feature documented in GitHub Wiki)
- [ ] UML class diagrams and component diagrams created and up-to-date
- [x] Documentation in realization created (source code)
- [x] Changelog created (Clear description in merge request)
- [x] There are no known bugs

**Technical Definition of Done**

- [x] Get references from other applications/websites
- [x] Create wireframe
- [x] Everything build out of Material UI components
- [x] New Material UI components capsulated via dependency injection in "@common/components"
- [x] Provide basic information pieces in comments
- [x] Establish interface to backend (if necessary) 
- [x] Use Skeleton components if something has to be fetched (if necessary)
- [x] Error management: Components should handle undefined inputs
- [x] Components should be resuable (if possible)
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met
- [x] Rendering is optimized

**Comment by theUpsider** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/HASKI-WS-63317fe9ca1e282770a9342a/issues/HASKI-Kempten/HASKI-Frontend/98?planning-poker) with Zenhub @DimitriB01 @juli-txt @Platura

**Comment by DimitriB01** [comment]
- Add as a new Component
- Used on call-back-error (Display message)

**Comment by DimitriB01** [comment]
Displayed at the top in the middle

**Comment by juli-txt** [comment]
`export type SnackbarProps = {
  autoHideDuration?: number;
  message?: string;
  severity?: SeverityType;
  open?: boolean;
};`

**Comment by juli-txt** [comment]
![Snackbars](https://github.com/HASKI-RAK/HASKI-Frontend/assets/106922840/1b3e6e34-28be-44cb-95da-2d7461a10c7e)
